#ifndef LCD_COMMANDS_H_INCLUDED
#define LCD_COMMANDS_H_INCLUDED


enum {
    LCD_COMM_NOP = 0x00,
    LCD_COMM_SOFT_RESET = 0x01,
    LCD_COMM_GET_POWER_MODE = 0x0A,
    LCD_COMM_GET_ADDRESS_MODE = 0x0B,
    LCD_COMM_GET_PIXEL_FORMAT = 0x0C,
    LCD_COMM_GET_DISPLAY_MODE = 0x0D,
    LCD_COMM_GET_SIGNAL_MODE = 0x0E,
    LCD_COMM_GET_DIAGNOSTIC_RESULT = 0x0F,
    LCD_COMM_ENTER_SLEEP_MODE = 0x10,
    LCD_COMM_EXIT_SLEEP_MODE = 0X11,
    LCD_COMM_ENTER_PARTIAL_MODE = 0x12,
    LCD_COMM_ENTER_NORMAL_MODE = 0x13,
    LCD_COMM_EXIT_INVERT_MODE = 0x20,
    LCD_COMM_ENTER_INVERT_MODE = 0x21,
    LCD_COMM_SET_DISPLAY_OFF = 0x28,
    LCD_COMM_SET_DISPLAY_ON = 0x29,
    LCD_COMM_SET_COLUMN_ADDRESS = 0x2A,
    LCD_COMM_SET_PAGE_ADDRESS = 0x2B,
    LCD_COMM_WRITE_MEMORY_START = 0x2C,
    LCD_COMM_READ_MEMORY_START = 0x2E,
    LCD_COMM_SET_PARTIAL_AREA = 0x30,
    LCD_COMM_SET_SCROLL_AREA = 0x33,
    LCD_COMM_SET_TEAR_OFF = 0x34,
    LCD_COMM_SET_TEAR_ON = 0x35,
    LCD_COMM_SET_ADDRESS_MODE = 0x36,
    LCD_COMM_SET_SCROLL_START = 0x37,
    LCD_COMM_EXIT_IDLE_MODE = 0x38,
    LCD_COMM_ENTER_IDLE_MODE = 0x39,
    LCD_COMM_SET_PIXEL_FORMAT = 0x3A,
    LCD_COMM_WRITE_MEMORY_CONTINUE = 0x3C,
    LCD_COMM_READ_MEMORY_CONTINUE = 0x3E,
    LCD_COMM_SET_TEAR_SCANLINE = 0x44,
    LCD_COMM_GET_SCANLINE = 0x45,
    LCD_COMM_READ_DDB_START = 0xA1,
    LCD_COMM_COMMAND_ACCESS_PROTECT = 0xB0,
    LCD_COMM_LOW_POWER_MODE_CONTROL = 0xB1,
    LCD_COMM_FRAME_MEMORY_ACCESS_AND_INTERFACE_SETTING = 0xB3,
    LCD_COMM_DISPLAY_MODE_AND_FRAME_MEMORY_WRITE_MODE_SETTING = 0xB4,
    LCD_COMM_DEVICE_CODE_READ = 0xBF,
    LCD_COMM_PANEL_DRIVING_SETTING = 0xC0,
    LCD_COMM_DISPLAY_TIMING_SETTING_FOR_NORMAL_MODE = 0xC1,
    LCD_COMM_DISPLAY_TIMING_SETTING_FOR_PARTIAL_MODE = 0xC2,
    LCD_COMM_DISPLAY_TIMING_SETTING_FOR_IDLE_MODE = 0xC3,
    LCD_COMM_FRAME_RATE_AND_INVERSION_CONTROL = 0xC5,
    LCD_COMM_INTERFACE_CONTROL = 0xC6,
    LCD_COMM_GAMMA_SETTING = 0xC8,
    LCD_COMM_POWER_SETTING = 0xD0,
    LCD_COMM_VCOM_CONTROL = 0xD1,
    LCD_COMM_POWER_SETTING_FOR_NORMAL_MODE = 0xD2,
    LCD_COMM_POWER_SETTING_FOR_PARTIAL_MODE = 0xD3,
    LCD_COMM_POWER_SETTING_FOR_IDLE_MODE = 0xD4,
    LCD_COMM_NV_MEMORY_WRITE = 0xE0,
    LCD_COMM_NV_MEMORY_CONTROL = 0xE1,
    LCD_COMM_NV_MEMORY_STATUS_READ = 0xE2,
    LCD_COMM_NV_MEMORY_PROTECTION = 0xE3
}eLCD_COMMAND;







void SoftReset(void);
void DisplayOn(void);
void DisplayOff(void);

#endif /* LCD_COMMANDS_H_INCLUDED */
